# Generated by Django 4.0 on 2021-12-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testappdjango', '0003_alter_mark_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_relate', related_query_name='teacher_filter', to='testappdjango.teacher'),
        ),
    ]
