# Generated by Django 3.2.8 on 2021-11-05 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fins', '0003_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
